"use client";
import { useEffect, useState } from "react";
import { getApiBaseUrl } from "@/lib/api-base-url";

type Condition = { id: string; stableCode: string; nameEn: string; nameAr?: string; reviewStatus: string; likelyCategoriesJson: unknown; differentialJson: unknown; redFlagsJson: unknown; nonDrugCareJson: unknown; genericOptions: Array<{ id: string; medication: { genericName: string }; bodyAreaSuitabilityJson: unknown; pregnancyLactationText?: string; reviewStatus: string; source: { title: string } }> };
const priorities = ["Acne", "Hyperpigmentation", "Melasma", "Eczema / dermatitis", "Psoriasis", "Fungal infection", "Rosacea", "Urticaria", "Alopecia", "Hirsutism", "Intertrigo", "Vulvar dermatology", "Sensitive-area pigmentation"];

export function DermatologyWorkspace() {
  const [query, setQuery] = useState(""); const [results, setResults] = useState<Condition[]>([]); const [status, setStatus] = useState("Search dermatologic condition, symptom, anatomy, mechanism, or generic medicine…");
  useEffect(() => { if (query.trim().length < 2) { setResults([]); return; } const timer = window.setTimeout(async () => { const token = sessionStorage.getItem("prijClinicToken"); const response = await fetch(`${getApiBaseUrl()}/dermatology/search?q=${encodeURIComponent(query)}`, { credentials: "include", headers: token ? { authorization: `Bearer ${token}` } : {} }).catch(() => null); if (!response?.ok) return setStatus("Dermatology reference search is unavailable for this role."); const data = await response.json(); setResults(data.results); setStatus(`${data.results.length} reviewed or review-pending topic(s). Doctor review required.`); }, 220); return () => clearTimeout(timer); }, [query]);
  return <section className="dermatology-workspace"><div className="panel pharmacology-search-sticky"><label><strong>Dermatology search</strong><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Condition, symptom, body area, mechanism, or generic…" /></label><p className="muted">{status}</p></div>
    <p className="notice safety-note"><strong>Assessment first.</strong> This reference does not diagnose or select treatment. Red flags and escalation must be reviewed before generic options—especially for external genital skin, mucosa, groin fold, axilla, inner thigh, and facial skin.</p>
    {!query ? <div className="dermatology-priority-grid">{priorities.map((topic) => <button key={topic} type="button" onClick={() => setQuery(topic)}>{topic}</button>)}</div> : null}
    {results.map((condition) => <article className="panel dermatology-condition" key={condition.id}><header><h2>{condition.nameEn}</h2>{condition.nameAr ? <p lang="ar" dir="rtl">{condition.nameAr}</p> : null}<span className="badge warning">{condition.reviewStatus}</span></header><section><h3>Red flags and escalation</h3><Structured value={condition.redFlagsJson} empty="No source-reviewed red flags are published." /></section><section><h3>Assessment and differential</h3><Structured value={condition.likelyCategoriesJson} empty="No source-reviewed assessment categories are published." /><Structured value={condition.differentialJson} empty="No source-reviewed differential is published." /></section><section><h3>Non-drug care</h3><Structured value={condition.nonDrugCareJson} empty="No source-reviewed non-drug guidance is published." /></section><section><h3>Reviewed generic options</h3>{condition.genericOptions.length ? condition.genericOptions.map((option) => <div key={option.id}><strong>{option.medication.genericName}</strong><Structured value={option.bodyAreaSuitabilityJson} empty="Body-area suitability not reviewed." /><p>{option.pregnancyLactationText}</p><small>Source: {option.source.title}</small></div>) : <p className="muted">No source-approved generic option is available. No universal treatment is implied.</p>}</section></article>)}
  </section>;
}
function Structured({ value, empty }: { value: unknown; empty: string }) { const items = Array.isArray(value) ? value : value && typeof value === "object" ? Object.values(value as Record<string, unknown>) : []; return items.length ? <ul>{items.map((item, index) => <li key={index}>{String(item)}</li>)}</ul> : <p className="muted">{empty}</p>; }
