"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { getApiBaseUrl } from "@/lib/api-base-url";
import { useI18n } from "@/i18n/useI18n";

type Source = { title: string; organization: string; sourceUrl?: string | null; versionLabel?: string | null };
type GenericOption = { id: string; medication: { id: string; genericName: string }; bodyAreaSuitabilityJson: unknown; pregnancyLactationText?: string | null; reviewStatus: string; source: Source };
type TopicContent = { overview?: string; typicalClinicalPattern?: string[]; importantHistoryQuestions?: string[]; suggestedExaminationFields?: string[]; bodyAreaConsiderations?: string[]; relevantInvestigations?: string[]; medicationClasses?: string[]; pregnancyLactationConsiderations?: string[] };
type Topic = { id: string; stableCode: string; nameEn: string; nameAr?: string | null; reviewStatus: string; likelyCategoriesJson: TopicContent; differentialJson: { prompts?: string[]; whenToRefer?: string[]; relatedTopics?: string[] }; redFlagsJson: unknown; nonDrugCareJson: unknown; source?: Source | null; genericOptions: GenericOption[] };

export function DermatologyWorkspace() {
  const { t, language, direction } = useI18n(); const [topics, setTopics] = useState<Topic[]>([]); const [query, setQuery] = useState(""); const [selectedId, setSelectedId] = useState(""); const [status, setStatus] = useState("");
  const filtered = useMemo(() => { const needle = query.trim().toLocaleLowerCase(); return needle ? topics.filter((topic) => `${topic.nameEn} ${topic.nameAr ?? ""} ${topic.stableCode}`.toLocaleLowerCase().includes(needle)) : topics; }, [topics, query]);
  const selected = topics.find((topic) => topic.id === selectedId) ?? null; const selectedIndex = filtered.findIndex((topic) => topic.id === selectedId);
  useEffect(() => { void load(); }, []);
  async function load() { const token = sessionStorage.getItem("prijClinicToken"); const response = await fetch(`${getApiBaseUrl()}/dermatology/atlas`, { credentials: "include", headers: token ? { authorization: `Bearer ${token}` } : {} }).catch(() => null); if (!response?.ok) return setStatus(t("noDermatologyTopicMatches")); const body = await response.json() as { conditions?: Topic[]; total?: number }; setTopics(body.conditions ?? []); setStatus(`${body.total ?? 0} ${t("localClinicalReviewRequired")}`); }
  function open(topic: Topic) { setSelectedId(topic.id); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function move(offset: number) { if (!filtered.length) return; const next = filtered[(selectedIndex + offset + filtered.length) % filtered.length]; if (next) open(next); }
  return <section className="dermatology-workspace" dir={direction}>
    <div className="panel pharmacology-search-sticky"><label htmlFor="dermatology-search"><strong>{t("dermatologySearch")}</strong></label><div className="inline-form"><input id="dermatology-search" dir="auto" value={query} onChange={(event) => { setQuery(event.target.value); setSelectedId(""); }} placeholder={t("dermatologySearch")} /><button className="button secondary" type="button" onClick={() => { setQuery(""); setSelectedId(""); }}>{t("reset")}</button></div><p className="muted" role="status">{status}</p></div>
    <p className="notice safety-note"><strong>{t("assessmentFirst")}.</strong> {t("dermatologySafety")}</p>
    {selected ? <TopicDetail topic={selected} onBack={() => setSelectedId("")} onPrevious={() => move(-1)} onNext={() => move(1)} /> : <><div className="section-heading"><div><h2>{t("topics")}</h2><p className="muted">{t("chooseDermatologyTopic")}</p></div><span className="badge">{filtered.length} / {topics.length}</span></div>{filtered.length ? <div className="dermatology-priority-grid">{filtered.map((topic) => <button key={topic.id} type="button" onClick={() => open(topic)}><strong>{language === "ar" && topic.nameAr ? topic.nameAr : topic.nameEn}</strong>{language !== "ar" && topic.nameAr ? <span lang="ar" dir="rtl">{topic.nameAr}</span> : null}<small>{topic.reviewStatus.replaceAll("_", " ")}</small></button>)}</div> : <p className="empty-state">{t("noDermatologyTopicMatches")}</p>}</>}
  </section>;
}

function TopicDetail({ topic, onBack, onPrevious, onNext }: { topic: Topic; onBack: () => void; onPrevious: () => void; onNext: () => void }) {
  const { t, language } = useI18n(); const content = topic.likelyCategoriesJson ?? {};
  return <article className="dermatology-topic-detail"><nav className="form-actions dermatology-topic-nav" aria-label={t("dermatologyKnowledgeTopic")}><button className="button secondary compact" type="button" onClick={onBack}>{t("backToTopics")}</button><button className="button secondary compact" type="button" onClick={onPrevious}>{t("previousTopic")}</button><button className="button secondary compact" type="button" onClick={onNext}>{t("nextTopic")}</button></nav>
    <header className="panel"><div className="section-heading"><div><p className="eyebrow">{t("dermatologyKnowledgeTopic")}</p><h2>{language === "ar" && topic.nameAr ? topic.nameAr : topic.nameEn}</h2>{language !== "ar" && topic.nameAr ? <p lang="ar" dir="rtl">{topic.nameAr}</p> : null}</div><span className="badge warning">{topic.reviewStatus.replaceAll("_", " ")}</span></div><p>{content.overview ?? t("sourceIncomplete")}</p>{topic.source ? <p className="muted">{t("sourceLabel")}: {topic.source.organization} · {topic.source.title} · {topic.source.versionLabel || "—"} {topic.source.sourceUrl ? <a href={topic.source.sourceUrl} target="_blank" rel="noreferrer">{t("openSource")}</a> : null}</p> : <p className="warning-text">{t("noSourceLinked")}</p>}</header>
    <div className="dermatology-topic-grid"><TopicCard title={t("redFlagsEscalation")} value={topic.redFlagsJson} tone="danger" />
      <section className="panel"><h3>{t("assessmentDifferential")}</h3><h4>{t("typicalClinicalPattern")}</h4><Structured value={content.typicalClinicalPattern} empty={t("sourceIncomplete")} /><h4>{t("importantHistoryQuestions")}</h4><Structured value={content.importantHistoryQuestions} empty={t("sourceIncomplete")} /><h4>{t("suggestedExaminationFields")}</h4><Structured value={content.suggestedExaminationFields} empty={t("sourceIncomplete")} /><h4>{t("differentialPrompts")}</h4><Structured value={topic.differentialJson?.prompts} empty={t("sourceIncomplete")} /></section>
      <TopicCard title={t("nonDrugCare")} value={topic.nonDrugCareJson} />
      <section className="panel"><h3>{t("reviewedGenericOptions")}</h3><p className="muted">{t("noUniversalTreatment")}</p><Structured value={content.medicationClasses} empty={t("noReviewedMedicationClass")} />{topic.genericOptions.length ? topic.genericOptions.map((option) => <article className="data-row" key={option.id}><strong>{option.medication.genericName}</strong><span className="badge">{option.reviewStatus.replaceAll("_", " ")}</span><small>{t("sourceLabel")}: {option.source.title}</small><Link href={`/prescriptions?medicationGenericId=${encodeURIComponent(option.medication.id)}`}>{t("prescription")}</Link></article>) : <p className="muted">{t("noMedicineApproved")}</p>}<Link className="button secondary compact" href="/medications/search">{t("openDrugAtlas")}</Link></section>
      <TopicCard title={t("bodyAreaConsiderations")} value={content.bodyAreaConsiderations} /><TopicCard title={t("relevantInvestigations")} value={content.relevantInvestigations} /><TopicCard title={t("pregnancyLactation")} value={content.pregnancyLactationConsiderations} /><TopicCard title={t("whenToRefer")} value={topic.differentialJson?.whenToRefer} /><TopicCard title={t("relatedTopics")} value={topic.differentialJson?.relatedTopics} />
    </div></article>;
}

function TopicCard({ title, value, tone }: { title: string; value: unknown; tone?: "danger" }) { const { t } = useI18n(); return <section className={`panel dermatology-topic-card ${tone ?? ""}`}><h3>{title}</h3><Structured value={value} empty={t("sourceIncomplete")} /></section>; }
function Structured({ value, empty }: { value: unknown; empty: string }) { const items = Array.isArray(value) ? value : typeof value === "string" ? [value] : value && typeof value === "object" ? Object.values(value as Record<string, unknown>).flatMap((item) => Array.isArray(item) ? item : [item]) : []; return items.length ? <ul>{items.map((item, index) => <li key={index}>{typeof item === "string" ? item : JSON.stringify(item)}</li>)}</ul> : <p className="muted">{empty}</p>; }
