export const supportedSourceConnectors = [
  "SFDA_OFFICIAL_DRUG_LIST_CONNECTOR",
  "EDA_EDDB_CONNECTOR",
  "UAE_EDE_DIRECTORY_CONNECTOR",
  "UAE_MOHAP_DIRECTORY_CONNECTOR",
  "YEMEN_OFFICIAL_UPLOAD_CONNECTOR",
  "RETAIL_PUBLIC_METADATA_CONNECTOR_TEMPLATE"
] as const;
