"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { getApiBaseUrl } from "@/lib/api-base-url";
import { AppShell } from "../../mvp-page";

type ServiceItem = { id: string; code: string; name: string; category: string; price: string | null; costAmount: string | null; doctorShareAmount: string | null; currency: string; active: boolean };
type Draft = { id: string; code: string; name: string; category: string; price: string; costAmount: string; doctorShareAmount: string; currency: string; reason: string };
const emptyDraft: Draft = { id: "", code: "", name: "", category: "", price: "", costAmount: "", doctorShareAmount: "", currency: "EGP", reason: "" };
const pageSize = 20;

export default function AdminServicesPage() {
  const [items, setItems] = useState<ServiceItem[]>([]); const [query, setQuery] = useState(""); const [statusFilter, setStatusFilter] = useState("active"); const [category, setCategory] = useState("all"); const [sort, setSort] = useState("name"); const [page, setPage] = useState(1); const [draft, setDraft] = useState<Draft | null>(null); const [status, setStatus] = useState("Loading services");
  const load = useCallback(async () => { const response = await request("/admin/services"); if (!response.ok) return setStatus(response.status === 403 ? "Owner/Admin access is required." : "Services could not be loaded."); const body = await response.json() as { services?: ServiceItem[] }; setItems(body.services ?? []); setStatus("Ready"); }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { setPage(1); }, [query, statusFilter, category, sort]);
  const categories = useMemo(() => [...new Set(items.map((item) => item.category))].sort(), [items]);
  const filtered = useMemo(() => items.filter((item) => (statusFilter === "all" || (statusFilter === "active") === item.active) && (category === "all" || item.category === category) && `${item.code} ${item.name} ${item.category}`.toLowerCase().includes(query.trim().toLowerCase())).sort((a, b) => sort === "category" ? a.category.localeCompare(b.category) || a.name.localeCompare(b.name) : sort === "price" ? Number(a.price ?? 0) - Number(b.price ?? 0) : a.name.localeCompare(b.name)), [items, query, statusFilter, category, sort]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / pageSize)); const visible = filtered.slice((page - 1) * pageSize, page * pageSize); const start = filtered.length ? (page - 1) * pageSize + 1 : 0; const end = Math.min(page * pageSize, filtered.length);
  async function save(event: FormEvent) { event.preventDefault(); if (!draft) return; const payload = { ...(draft.id ? {} : { code: draft.code }), name: draft.name, category: draft.category, price: optionalNumber(draft.price), costAmount: optionalNumber(draft.costAmount), doctorShareAmount: optionalNumber(draft.doctorShareAmount), currency: draft.currency, reason: draft.reason || undefined }; const response = await request(draft.id ? `/admin/services/${draft.id}` : "/admin/services", draft.id ? "PATCH" : "POST", payload); if (!response.ok) return setStatus(await responseError(response)); setDraft(null); setStatus("Service saved and audited."); await load(); }
  async function changeStatus(item: ServiceItem) { const reason = window.prompt(`Reason to ${item.active ? "deactivate" : "reactivate"} this service`)?.trim(); if (!reason) return; const response = await request(`/admin/services/${item.id}/${item.active ? "deactivate" : "reactivate"}`, "POST", { reason, confirmation: "CONFIRM" }); setStatus(response.ok ? "Service status changed and audited." : await responseError(response)); if (response.ok) await load(); }
  return <AppShell><section className="page-header"><div className="header-row"><div><p className="eyebrow">Owner / Admin</p><h1>Services & Pricing</h1><p className="muted">Search, price, edit, deactivate, and restore real service catalog entries.</p></div><button className="button" type="button" onClick={() => setDraft(emptyDraft)}>New service</button></div></section>
    <section className="panel compact-panel"><div className="toolbar"><label>Search<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Code, service, category" /></label><label>Category<select value={category} onChange={(event) => setCategory(event.target.value)}><option value="all">All categories</option>{categories.map((value) => <option key={value}>{value}</option>)}</select></label><label>Status<select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option value="active">Active</option><option value="inactive">Inactive</option><option value="all">All</option></select></label><label>Sort<select value={sort} onChange={(event) => setSort(event.target.value)}><option value="name">Name</option><option value="category">Category</option><option value="price">Price</option></select></label></div><p className="notice" role="status">{status}</p></section>
    <section className="panel"><div className="section-heading"><h2>Service catalog</h2><span className="badge">{start}-{end} of {filtered.length}</span></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Code</th><th>Service</th><th>Category</th><th>Price</th><th>Cost</th><th>Doctor share</th><th>Status</th><th>Actions</th></tr></thead><tbody>{visible.map((item) => <tr key={item.id}><td>{item.code}</td><td><strong>{item.name}</strong></td><td>{item.category}</td><td>{money(item.price, item.currency)}</td><td>{money(item.costAmount, item.currency)}</td><td>{money(item.doctorShareAmount, item.currency)}</td><td><span className={`badge ${item.active ? "accent" : "warning"}`}>{item.active ? "Active" : "Inactive"}</span></td><td><div className="form-actions"><button className="button secondary compact" type="button" onClick={() => setDraft({ id: item.id, code: item.code, name: item.name, category: item.category, price: item.price ?? "", costAmount: item.costAmount ?? "", doctorShareAmount: item.doctorShareAmount ?? "", currency: item.currency, reason: "" })}>Edit</button><button className="button secondary compact" type="button" onClick={() => void changeStatus(item)}>{item.active ? "Deactivate" : "Restore"}</button></div></td></tr>)}</tbody></table></div>{!visible.length ? <p className="empty-state compact">No services match these filters.</p> : null}<div className="pagination-row"><button className="button secondary compact" disabled={page <= 1} onClick={() => setPage((value) => value - 1)} type="button">Previous</button><span>Page {page} of {pageCount}</span><button className="button secondary compact" disabled={page >= pageCount} onClick={() => setPage((value) => value + 1)} type="button">Next</button></div></section>
    {draft ? <div className="admin-editor-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setDraft(null); }}><section className="admin-editor-drawer" role="dialog" aria-modal="true" aria-labelledby="service-editor-title"><div className="section-heading"><h2 id="service-editor-title">{draft.id ? "Edit service" : "Create service"}</h2><button className="button secondary compact" type="button" onClick={() => setDraft(null)}>Close</button></div><form className="form-grid" onSubmit={save}><label>Code<input disabled={Boolean(draft.id)} required value={draft.code} onChange={(event) => setDraft({ ...draft, code: event.target.value })} /></label><label>Service name<input required value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></label><label>Category<input required value={draft.category} onChange={(event) => setDraft({ ...draft, category: event.target.value })} /></label><label>Currency<input required value={draft.currency} onChange={(event) => setDraft({ ...draft, currency: event.target.value })} /></label><label>Price<input min="0" step="0.01" type="number" value={draft.price} onChange={(event) => setDraft({ ...draft, price: event.target.value })} /></label><label>Cost<input min="0" step="0.01" type="number" value={draft.costAmount} onChange={(event) => setDraft({ ...draft, costAmount: event.target.value })} /></label><label>Doctor share<input min="0" step="0.01" type="number" value={draft.doctorShareAmount} onChange={(event) => setDraft({ ...draft, doctorShareAmount: event.target.value })} /></label><label className="wide">Change reason<input value={draft.reason} onChange={(event) => setDraft({ ...draft, reason: event.target.value })} placeholder="Required when changing price" /></label><div className="form-actions wide"><button className="button" type="submit">Save</button><button className="button secondary" type="button" onClick={() => setDraft(null)}>Cancel</button></div></form></section></div> : null}
  </AppShell>;
}

function optionalNumber(value: string) { return value.trim() ? Number(value) : undefined; }
function money(value: string | null, currency: string) { return value === null ? "Not set" : `${value} ${currency}`; }
async function request(path: string, method = "GET", payload?: object) { const token = sessionStorage.getItem("prijClinicToken"); return fetch(`${getApiBaseUrl()}${path}`, { method, credentials: "include", headers: { ...(payload ? { "content-type": "application/json" } : {}), ...(token ? { authorization: `Bearer ${token}` } : {}) }, body: payload ? JSON.stringify(payload) : undefined }).catch(() => new Response(null, { status: 503 })); }
async function responseError(response: Response) { const body = await response.json().catch(() => ({})) as { message?: string | string[] }; return Array.isArray(body.message) ? body.message[0] ?? "Service action failed." : body.message ?? "Service action failed."; }
