ALTER TABLE "AdverseEffect" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "AntimicrobialSpectrum" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "Caution" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "Contraindication" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "DoseFormula" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "FormulaVersion" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "GenericMedicationFamilyMembership" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "GuidelineSummary" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "GuidelineSummaryCitation" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "GuidelineSummarySection" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "HepaticGuidance" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "Interaction" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "MechanismSummary" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "MedicationAlias" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "MonitoringRequirement" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "Patient" ALTER COLUMN "qrToken" DROP DEFAULT;
ALTER TABLE "PharmacodynamicSummary" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "PharmacokineticSummary" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "PharmacologySource" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "PregnancyLactationProfile" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "RenalGuidance" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "ReviewRecord" ALTER COLUMN "id" DROP DEFAULT;

CREATE INDEX "AdverseEffect_medicationGenericId_severity_idx" ON "AdverseEffect"("medicationGenericId", "severity");
CREATE INDEX "AdverseEffect_normalizedName_idx" ON "AdverseEffect"("normalizedName");
CREATE INDEX "AdverseEffect_sourceId_idx" ON "AdverseEffect"("sourceId");
CREATE INDEX "AntimicrobialSpectrum_gramPositive_idx" ON "AntimicrobialSpectrum"("gramPositive");
CREATE INDEX "AntimicrobialSpectrum_gramNegative_idx" ON "AntimicrobialSpectrum"("gramNegative");
CREATE INDEX "AntimicrobialSpectrum_pseudomonas_idx" ON "AntimicrobialSpectrum"("pseudomonas");
CREATE INDEX "AntimicrobialSpectrum_mrsa_idx" ON "AntimicrobialSpectrum"("mrsa");
CREATE INDEX "AntimicrobialSpectrum_enterococcus_idx" ON "AntimicrobialSpectrum"("enterococcus");
CREATE INDEX "Caution_medicationGenericId_idx" ON "Caution"("medicationGenericId");
CREATE INDEX "Caution_normalizedText_idx" ON "Caution"("normalizedText");
CREATE INDEX "Caution_sourceId_idx" ON "Caution"("sourceId");
CREATE INDEX "Contraindication_medicationGenericId_classification_idx" ON "Contraindication"("medicationGenericId", "classification");
CREATE INDEX "Contraindication_normalizedName_idx" ON "Contraindication"("normalizedName");
CREATE INDEX "Contraindication_sourceId_idx" ON "Contraindication"("sourceId");
CREATE INDEX "DoseFormula_medicationGenericId_idx" ON "DoseFormula"("medicationGenericId");
CREATE INDEX "DoseFormula_calculatorType_active_idx" ON "DoseFormula"("calculatorType", "active");
CREATE INDEX "FormulaVersion_sourceId_idx" ON "FormulaVersion"("sourceId");
CREATE INDEX "FormulaVersion_reviewerUserId_idx" ON "FormulaVersion"("reviewerUserId");
CREATE INDEX "GenericMedicationFamilyMembership_sourceId_idx" ON "GenericMedicationFamilyMembership"("sourceId");
CREATE INDEX "HepaticGuidance_medicationGenericId_adjustmentStatus_idx" ON "HepaticGuidance"("medicationGenericId", "adjustmentStatus");
CREATE INDEX "HepaticGuidance_sourceId_idx" ON "HepaticGuidance"("sourceId");
CREATE INDEX "Interaction_primaryGenericId_severity_idx" ON "Interaction"("primaryGenericId", "severity");
CREATE INDEX "Interaction_secondaryGenericId_idx" ON "Interaction"("secondaryGenericId");
CREATE INDEX "Interaction_normalizedSearchText_idx" ON "Interaction"("normalizedSearchText");
CREATE INDEX "Interaction_sourceId_idx" ON "Interaction"("sourceId");
CREATE INDEX "MechanismSummary_medicationGenericId_reviewStatus_idx" ON "MechanismSummary"("medicationGenericId", "reviewStatus");
CREATE INDEX "MechanismSummary_sourceId_idx" ON "MechanismSummary"("sourceId");
CREATE INDEX "MedicationAlias_scopeType_scopeId_idx" ON "MedicationAlias"("scopeType", "scopeId");
CREATE INDEX "MonitoringRequirement_medicationGenericId_idx" ON "MonitoringRequirement"("medicationGenericId");
CREATE INDEX "MonitoringRequirement_normalizedParameter_idx" ON "MonitoringRequirement"("normalizedParameter");
CREATE INDEX "MonitoringRequirement_sourceId_idx" ON "MonitoringRequirement"("sourceId");
CREATE INDEX "PharmacodynamicSummary_medicationGenericId_reviewStatus_idx" ON "PharmacodynamicSummary"("medicationGenericId", "reviewStatus");
CREATE INDEX "PharmacodynamicSummary_sourceId_idx" ON "PharmacodynamicSummary"("sourceId");
CREATE INDEX "PharmacokineticSummary_medicationGenericId_reviewStatus_idx" ON "PharmacokineticSummary"("medicationGenericId", "reviewStatus");
CREATE INDEX "PharmacokineticSummary_sourceId_idx" ON "PharmacokineticSummary"("sourceId");
CREATE INDEX "PharmacologySource_organization_reviewStatus_idx" ON "PharmacologySource"("organization", "reviewStatus");
CREATE INDEX "PharmacologySource_provenanceType_idx" ON "PharmacologySource"("provenanceType");
CREATE INDEX "PregnancyLactationProfile_medicationGenericId_reviewStatus_idx" ON "PregnancyLactationProfile"("medicationGenericId", "reviewStatus");
CREATE INDEX "PregnancyLactationProfile_sourceId_idx" ON "PregnancyLactationProfile"("sourceId");
CREATE INDEX "RenalGuidance_medicationGenericId_adjustmentStatus_idx" ON "RenalGuidance"("medicationGenericId", "adjustmentStatus");
CREATE INDEX "RenalGuidance_sourceId_idx" ON "RenalGuidance"("sourceId");
CREATE INDEX "ReviewRecord_sourceId_idx" ON "ReviewRecord"("sourceId");
CREATE INDEX "ReviewRecord_reviewerUserId_reviewedAt_idx" ON "ReviewRecord"("reviewerUserId", "reviewedAt");

ALTER INDEX "GenericMedicationFamilyMembership_medicationGenericId_familyId_" RENAME TO "GenericMedicationFamilyMembership_medicationGenericId_famil_key";
ALTER INDEX "MedicationAlias_medicationGenericId_normalizedAlias_scopeType_s" RENAME TO "MedicationAlias_medicationGenericId_normalizedAlias_scopeTy_key";
