-- Add canonical values without rewriting ambiguous historical patient records.
ALTER TYPE "PatientType" ADD VALUE IF NOT EXISTS 'OBSTETRIC';
ALTER TYPE "PatientType" ADD VALUE IF NOT EXISTS 'HIGH_RISK_OBSTETRIC';
ALTER TYPE "PatientType" ADD VALUE IF NOT EXISTS 'GYNECOLOGY';
ALTER TYPE "PatientType" ADD VALUE IF NOT EXISTS 'POSTPARTUM';
ALTER TYPE "PatientType" ADD VALUE IF NOT EXISTS 'PREVENTIVE_WELL_WOMAN';
ALTER TYPE "PatientType" ADD VALUE IF NOT EXISTS 'OTHER';
