export const receptionCopy = {
  en: {
    eyebrow: "Reception",
    title: "Reception Command Center",
    subtitle: "Find the patient once, then complete today’s front-desk actions from one workspace.",
    refresh: "Refresh",
    todayFlow: "Today’s flow",
    appointments: "Appointments",
    checkedIn: "Checked in",
    waiting: "Waiting",
    urgent: "Urgent",
    findPatient: "Find patient",
    newPatient: "New patient",
    checkIn: "Check in",
    bookAppointment: "Book appointment",
    openQueue: "Open queue",
    permanentQr: "Permanent QR",
    patientContext: "Patient context",
    patientContextHelp: "Search by name, phone, MRN, or permanent QR.",
    selectedPatient: "Selected patient",
    openProfile: "Open profile",
    clearSelection: "Clear selection",
    patientActions: "Patient actions",
    selectPatientFirst: "Select a patient to enable check-in.",
    alreadyWaiting: "This patient is already in today’s waiting line.",
    visitTypeRequired: "Select a visit type first.",
    addToWaiting: "Add to waiting line",
    addingToWaiting: "Adding to waiting line…",
    addedToWaiting: "Patient added to the waiting line.",
    queueUpdateFailed: "The waiting line could not be updated safely.",
    appointmentDate: "Date",
    appointmentTime: "Time",
    appointmentDuration: "Duration",
    appointmentNotes: "Optional reception note",
    today: "Today",
    tomorrow: "Tomorrow",
    scheduleAppointment: "Schedule appointment",
    schedulingAppointment: "Scheduling appointment…",
    appointmentSaved: "Appointment scheduled.",
    appointmentFailed: "The appointment could not be scheduled.",
    invalidAppointmentTime: "Choose a valid appointment date and time.",
    todayAppointments: "Today’s appointments",
    liveWaitingLine: "Live waiting line",
    queuePreview: "Queue preview",
    nextPatient: "Next",
    nextToDoctor: "Next to doctor",
    noPatientWaiting: "No patient waiting",
    noAppointments: "No appointments scheduled for today.",
    noQueue: "No active waiting-line entries.",
    select: "Select",
    queueNumber: "Queue",
    status: "Status",
    visitType: "Visit type",
    durationMinutes: "minutes",
    branchScoped: "Branch scoped",
    loading: "Loading reception workspace…",
    partialData: "Some live reception data is temporarily unavailable. Existing records were not changed.",
    scheduled: "Scheduled",
    cancelled: "Cancelled",
    completed: "Completed",
    called: "With doctor",
    checkedInStatus: "Checked in",
    waitingStatus: "Waiting"
  },
  ar: {
    eyebrow: "الاستقبال",
    title: "مركز عمل الاستقبال",
    subtitle: "ابحث عن المريضة مرة واحدة، ثم نفّذ مهام الاستقبال اليومية من مساحة عمل واحدة.",
    refresh: "تحديث",
    todayFlow: "حركة اليوم",
    appointments: "المواعيد",
    checkedIn: "تم الحضور",
    waiting: "في الانتظار",
    urgent: "مستعجل",
    findPatient: "البحث عن مريضة",
    newPatient: "مريضة جديدة",
    checkIn: "تسجيل الحضور",
    bookAppointment: "حجز موعد",
    openQueue: "فتح قائمة الانتظار",
    permanentQr: "الرمز الدائم",
    patientContext: "بيانات المريضة المحددة",
    patientContextHelp: "ابحث بالاسم أو الهاتف أو رقم الملف أو الرمز الدائم.",
    selectedPatient: "المريضة المحددة",
    openProfile: "فتح الملف",
    clearSelection: "إلغاء التحديد",
    patientActions: "إجراءات المريضة",
    selectPatientFirst: "حدد مريضة لتفعيل تسجيل الحضور.",
    alreadyWaiting: "هذه المريضة موجودة بالفعل في قائمة انتظار اليوم.",
    visitTypeRequired: "اختر نوع الزيارة أولاً.",
    addToWaiting: "إضافة إلى قائمة الانتظار",
    addingToWaiting: "جارٍ الإضافة إلى قائمة الانتظار…",
    addedToWaiting: "تمت إضافة المريضة إلى قائمة الانتظار.",
    queueUpdateFailed: "تعذر تحديث قائمة الانتظار بأمان.",
    appointmentDate: "التاريخ",
    appointmentTime: "الوقت",
    appointmentDuration: "المدة",
    appointmentNotes: "ملاحظة استقبال اختيارية",
    today: "اليوم",
    tomorrow: "غداً",
    scheduleAppointment: "تأكيد حجز الموعد",
    schedulingAppointment: "جارٍ حجز الموعد…",
    appointmentSaved: "تم حجز الموعد.",
    appointmentFailed: "تعذر حجز الموعد.",
    invalidAppointmentTime: "اختر تاريخاً ووقتاً صالحين للموعد.",
    todayAppointments: "مواعيد اليوم",
    liveWaitingLine: "قائمة الانتظار المباشرة",
    queuePreview: "ملخص قائمة الانتظار",
    nextPatient: "التالي",
    nextToDoctor: "التالي للطبيب",
    noPatientWaiting: "لا توجد مريضة في الانتظار",
    noAppointments: "لا توجد مواعيد مسجلة اليوم.",
    noQueue: "لا توجد حالات نشطة في قائمة الانتظار.",
    select: "تحديد",
    queueNumber: "رقم الانتظار",
    status: "الحالة",
    visitType: "نوع الزيارة",
    durationMinutes: "دقيقة",
    branchScoped: "حسب الفرع",
    loading: "جارٍ تحميل مساحة الاستقبال…",
    partialData: "بعض بيانات الاستقبال المباشرة غير متاحة مؤقتاً. لم يتم تغيير السجلات الحالية.",
    scheduled: "محجوز",
    cancelled: "ملغي",
    completed: "مكتمل",
    called: "مع الطبيب",
    checkedInStatus: "تم الحضور",
    waitingStatus: "في الانتظار"
  }
} as const;

export const receptionWorkflowCopy = {
  en: { checkIn: "Check-in", todayAppointments: "Today’s appointments", bookAppointment: "Book appointment", paymentStatus: "Payment status" },
  ar: { checkIn: "تسجيل الحضور", todayAppointments: "مواعيد اليوم", bookAppointment: "حجز موعد", paymentStatus: "حالة الدفع" }
} as const;
