export const receptionCopy = {
  en: {
    eyebrow: "Reception", title: "Reception Home", receptionActions: "Reception actions", searchPatient: "Search patient", searchPlaceholder: "Search by name, phone, file number, or QR", newPatient: "New Patient", returningPatientQr: "Returning Patient / QR", queue: "Queue", appointments: "Appointments", queueNow: "Queue preview", waiting: "Waiting", urgent: "Urgent", nextPatient: "Next patient", noPatientWaiting: "No patient waiting", findPatient: "Find patient", refresh: "Refresh", noPhone: "No phone", searchToFind: "Search to find a returning patient.", noMatch: "No matching patient found.", alreadyInQueue: "Already in queue — position", alreadyWithDoctor: "Patient is already with the doctor", openReceptionProfile: "Open reception profile", openQueue: "Open queue", addToQueue: "Add to queue", queuePreview: "Waiting preview", waitingDurationNotRecorded: "Waiting duration not recorded", selectPatientVisitType: "Select a patient and visit type first", addingToQueue: "Adding to queue", patientAddedToQueue: "Patient added to queue", couldNotAddToQueue: "Could not add patient to queue"
  },
  ar: {
    eyebrow: "الاستقبال", title: "الرئيسية — الاستقبال", receptionActions: "إجراءات الاستقبال", searchPatient: "البحث عن مريضة", searchPlaceholder: "البحث بالاسم أو الهاتف أو رقم الملف أو QR", newPatient: "مريضة جديدة", returningPatientQr: "مريضة مسجلة / QR", queue: "قائمة الانتظار", appointments: "المواعيد", queueNow: "ملخص قائمة الانتظار", waiting: "في الانتظار", urgent: "عاجل", nextPatient: "المريضة التالية", noPatientWaiting: "لا توجد مريضة في الانتظار", findPatient: "البحث عن مريضة", refresh: "تحديث", noPhone: "لا يوجد هاتف", searchToFind: "ابحثي عن مريضة مسجلة.", noMatch: "لا توجد مريضة مطابقة.", alreadyInQueue: "موجودة بالفعل في قائمة الانتظار — الترتيب", alreadyWithDoctor: "المريضة موجودة بالفعل مع الطبيب", openReceptionProfile: "فتح ملف الاستقبال", openQueue: "فتح قائمة الانتظار", addToQueue: "إضافة إلى قائمة الانتظار", queuePreview: "معاينة قائمة الانتظار", waitingDurationNotRecorded: "مدة الانتظار غير مسجلة", selectPatientVisitType: "اختاري المريضة ونوع الزيارة أولاً", addingToQueue: "جارٍ الإضافة إلى قائمة الانتظار", patientAddedToQueue: "تمت إضافة المريضة إلى قائمة الانتظار", couldNotAddToQueue: "تعذرت إضافة المريضة إلى قائمة الانتظار"
  }
} as const;

export const receptionWorkflowCopy = {
  en: { checkIn: "Check-in", todayAppointments: "Today’s appointments", bookAppointment: "Book appointment", paymentStatus: "Payment status" },
  ar: { checkIn: "تسجيل الحضور", todayAppointments: "مواعيد اليوم", bookAppointment: "حجز موعد", paymentStatus: "حالة الدفع" }
} as const;
