export enum Role {
  OWNER = "OWNER",
  ADMIN = "ADMIN",
  DOCTOR = "DOCTOR",
  NURSE = "NURSE",
  RECEPTIONIST = "RECEPTIONIST",
  ACCOUNTANT = "ACCOUNTANT"
}

export enum Action {
  PATIENT_VIEW = "PATIENT_VIEW",
  PATIENT_REGISTER = "PATIENT_REGISTER",
  PATIENT_CREATE_QUICK = "PATIENT_CREATE_QUICK",
  PATIENT_UPDATE_ADMIN = "PATIENT_UPDATE_ADMIN",
  APPOINTMENT_MANAGE = "APPOINTMENT_MANAGE",
  QUEUE_CHECKIN = "QUEUE_CHECKIN",
  QUEUE_STATUS_UPDATE = "QUEUE_STATUS_UPDATE",
  QUEUE_CANCEL = "QUEUE_CANCEL",
  QUEUE_RESTORE = "QUEUE_RESTORE",
  QUEUE_START_VISIT = "QUEUE_START_VISIT",
  VISIT_START = "VISIT_START",
  VISIT_RESUME = "VISIT_RESUME",
  VISIT_FINISH = "VISIT_FINISH",
  ENCOUNTER_CREATE = "ENCOUNTER_CREATE",
  ENCOUNTER_EDIT_DRAFT = "ENCOUNTER_EDIT_DRAFT",
  PRESCRIPTION_DRAFT_CREATE = "PRESCRIPTION_DRAFT_CREATE",
  PRESCRIPTION_EDIT_DRAFT = "PRESCRIPTION_EDIT_DRAFT",
  PRESCRIPTION_PRINT = "PRESCRIPTION_PRINT",
  PRESCRIPTION_SIGN = "PRESCRIPTION_SIGN",
  INVESTIGATION_REQUEST = "INVESTIGATION_REQUEST",
  INVESTIGATION_RESULT_REVIEW = "INVESTIGATION_RESULT_REVIEW",
  ULTRASOUND_RECORD = "ULTRASOUND_RECORD",
  FOLLOWUP_CREATE = "FOLLOWUP_CREATE",
  PRINT_CLINICAL_SUMMARY = "PRINT_CLINICAL_SUMMARY",
  AI_DRAFT_VIEW = "AI_DRAFT_VIEW",
  AI_APPROVE = "AI_APPROVE",
  VITALS_RECORD = "VITALS_RECORD",
  PAYMENT_COLLECT = "PAYMENT_COLLECT",
  PAYMENT_VIEW_OWN_DAY = "PAYMENT_VIEW_OWN_DAY",
  BILLING_VIEW = "BILLING_VIEW",
  BILLING_MANAGE = "BILLING_MANAGE",
  FINANCE_REPORT_VIEW = "FINANCE_REPORT_VIEW",
  ADMIN_SETTINGS = "ADMIN_SETTINGS",
  USER_MANAGE = "USER_MANAGE",
  SERVICE_CATALOG_MANAGE = "SERVICE_CATALOG_MANAGE",
  AUDIT_VIEW = "AUDIT_VIEW",
  PROTOCOL_VERIFY = "PROTOCOL_VERIFY",
  CONSENT_MANAGE = "CONSENT_MANAGE",
  CLINICAL_OVERRIDE_WITH_REASON = "CLINICAL_OVERRIDE_WITH_REASON",
  ADMIN_OVERRIDE_WITH_REASON = "ADMIN_OVERRIDE_WITH_REASON"
}

export const ROLE_PERMISSIONS: Record<Role, Action[]> = {
  [Role.OWNER]: Object.values(Action),
  [Role.ADMIN]: [
    Action.PATIENT_VIEW,
    Action.PATIENT_REGISTER,
    Action.PATIENT_UPDATE_ADMIN,
    Action.APPOINTMENT_MANAGE,
    Action.QUEUE_CHECKIN,
    Action.QUEUE_STATUS_UPDATE,
    Action.QUEUE_CANCEL,
    Action.QUEUE_RESTORE,
    Action.BILLING_VIEW,
    Action.BILLING_MANAGE,
    Action.PAYMENT_COLLECT,
    Action.PAYMENT_VIEW_OWN_DAY,
    Action.FINANCE_REPORT_VIEW,
    Action.ADMIN_SETTINGS,
    Action.USER_MANAGE,
    Action.SERVICE_CATALOG_MANAGE,
    Action.AUDIT_VIEW,
    Action.PROTOCOL_VERIFY,
    Action.CONSENT_MANAGE,
    Action.ADMIN_OVERRIDE_WITH_REASON
  ],
  [Role.DOCTOR]: [
    Action.PATIENT_VIEW,
    Action.PATIENT_CREATE_QUICK,
    Action.APPOINTMENT_MANAGE,
    Action.QUEUE_START_VISIT,
    Action.VISIT_START,
    Action.VISIT_RESUME,
    Action.VISIT_FINISH,
    Action.ENCOUNTER_CREATE,
    Action.ENCOUNTER_EDIT_DRAFT,
    Action.PRESCRIPTION_DRAFT_CREATE,
    Action.PRESCRIPTION_EDIT_DRAFT,
    Action.PRESCRIPTION_PRINT,
    Action.PRESCRIPTION_SIGN,
    Action.INVESTIGATION_REQUEST,
    Action.INVESTIGATION_RESULT_REVIEW,
    Action.ULTRASOUND_RECORD,
    Action.FOLLOWUP_CREATE,
    Action.PRINT_CLINICAL_SUMMARY,
    Action.AI_DRAFT_VIEW,
    Action.AI_APPROVE,
    Action.CONSENT_MANAGE,
    Action.CLINICAL_OVERRIDE_WITH_REASON
  ],
  [Role.NURSE]: [Action.PATIENT_VIEW, Action.QUEUE_CHECKIN, Action.QUEUE_STATUS_UPDATE, Action.VITALS_RECORD, Action.AI_DRAFT_VIEW],
  [Role.RECEPTIONIST]: [
    Action.PATIENT_REGISTER,
    Action.PATIENT_VIEW,
    Action.APPOINTMENT_MANAGE,
    Action.QUEUE_CHECKIN,
    Action.QUEUE_STATUS_UPDATE,
    Action.QUEUE_CANCEL,
    Action.PAYMENT_COLLECT,
    Action.PAYMENT_VIEW_OWN_DAY
  ],
  [Role.ACCOUNTANT]: [
    Action.PATIENT_VIEW,
    Action.BILLING_VIEW,
    Action.BILLING_MANAGE,
    Action.PAYMENT_COLLECT,
    Action.PAYMENT_VIEW_OWN_DAY,
    Action.FINANCE_REPORT_VIEW
  ]
};

export function hasPermission(role: Role, action: Action): boolean {
  return ROLE_PERMISSIONS[role]?.includes(action) ?? false;
}

export function normalizeRoleName(role: string): Role | null {
  const normalized = role.trim().toUpperCase().replace(/[\s-]+/g, "_");
  if (normalized === "RECEPTION") return Role.RECEPTIONIST;
  return Object.values(Role).includes(normalized as Role) ? (normalized as Role) : null;
}

export function hasAnyRolePermission(roles: string[], action: Action): boolean {
  return roles.some((role) => {
    const normalized = normalizeRoleName(role);
    return normalized ? hasPermission(normalized, action) : false;
  });
}
