$ErrorActionPreference = "Stop"

Write-Host "v0.9.3 Release Candidate QA Pack"
Write-Host ""
Write-Host "Docs to open:"
Write-Host "- docs/V0_9_3_RELEASE_CANDIDATE.md"
Write-Host "- docs/V0_9_3_MANUAL_BROWSER_QA_CHECKLIST.md"
Write-Host "- docs/V0_9_3_ROLE_QA_CHECKLIST.md"
Write-Host "- docs/V0_9_3_RELEASE_NOTES_DRAFT.md"
Write-Host "- docs/CURRENT_STATUS.md"
Write-Host "- docs/NEXT_STEPS.md"
Write-Host "- docs/KNOWN_LIMITATIONS.md"
Write-Host ""
Write-Host "Commands to run after returning home and starting Docker Desktop:"
Write-Host "npm run dev:diagnose"
Write-Host "npm run test:v093:release"
Write-Host ""
Write-Host "After local validation passes, complete manual browser QA before release tagging."
Write-Host ""
Write-Host "This helper is read-only. It does not mutate files, commit, tag, push, read secrets, or print secrets."
Write-Host "Do not use real patient data, a real payment gateway, external AI, or autonomous prescribing."
